#!/usr/bin/env ruby

require 'fileutils'

class BuildLuadec
  include FileUtils

  def download_sources
    mkdir_p "src"
    system "wget -nv -nc http://www.lua.org/ftp/lua-5.1.4.tar.gz -O src/lua-5.1.4.tar.gz"
    system "wget -nv -nc http://luaforge.net/frs/download.php/4008/luadec51_2.0.tgz -O src/luadec51_2.0.tgz"
  end

  def prepare_build_area
    rm_rf "build"
    mkdir_p "build"
  end

  def unpack_and_patch_sources
    system "tar -C build -xz <src/lua-5.1.4.tar.gz"
    system "tar -C build -xz <src/luadec51_2.0.tgz"
    system "patch -p0 <lua_etw.diff"
  end

  def build_lua
    Dir.chdir("build/lua-5.1.4/src") do
      if osx?
        system "make all MYCFLAGS='-m32 -DLUA_USE_LINUX' MYLIBS='-m32 -lreadline' MYLDFLAGS='-m32'"
      elsif cygwin?
        system "make generic"
      else # Linux
        system "make all MYCFLAGS='-DLUA_USE_LINUX -m32' MYLIBS='-Wl,-E -ldl -lreadline -lhistory -lncurses' MYLDFLAGS='-m32'"
      end
    end
  end

  def cflags
    if osx?
      "-w -g -m32"
    elsif cygwin?
      "-w -g"
    else
      "-w -DLUA_USE_LINUX -g -m32"
    end
  end

  def build_luadec
    Dir.chdir("build/luadec") do
      system "gcc #{cflags} -I../lua-5.1.4/src *.c -c"
      system "gcc #{cflags} *.o ../lua-5.1.4/src/liblua.a -lm -o ../../luadec"
    end
  end

  def run
    download_sources
    prepare_build_area
    unpack_and_patch_sources
    build_lua
    build_luadec
  end

  def osx?
    `uname`.chomp == 'Darwin'
  end

  def cygwin?
    `uname` =~ /cygwin/i
  end
end

BuildLuadec.new.run
