require "lib/file_format_detection"
require "fileutils"

# i386-darwin9.8.0/1.9.3
# Seems to have some bug with unpacking long series of floats
# ???

RUBY_VERSIONS = {
  "18"  => ["Ruby 1.8",  "ruby"],
#  "19"  => ["Ruby 1.9",  "ruby1.9"],
  "j18" => ["JRuby 1.8", "jruby --1.8"],
  "j19" => ["JRuby 1.9", "jruby --1.9"],
}

RUBY_VERSIONS.each{|name,(dsc,cmd)|
  desc "Run unit tests on #{dsc}"
  task "test:#{name}" do
    system "#{cmd} ./test.rb"
  end

  desc "Run samples tests on #{dsc}"
  task "test:samples:#{name}" do
    system "#{cmd} ./test_samples.rb"
  end
}

task "default" => "test"
task "test" => "test:18"
task "test:samples" => "test:samples:18"
task "test:samples:all" => RUBY_VERSIONS.keys.map{|name| "test:samples:#{name}"}
task "test:all" => RUBY_VERSIONS.keys.map{|name| "test:#{name}"}


# Feel free to pick different samples
desc "Verify that samples/ directory has a sample of each format (not distributed for copyright reasons)"
task :samples do
  FileFormatDetection.new("samples").verify_samples!
end

desc "Copy samples of each format from your ETW installation"
namespace :samples do
  task :get do
    FileFormatDetection.new("samples").get_missing_samples!
  end
end

