#!/usr/bin/env ruby

require "pp"

class Float
  def pretty_single
    rv = (((100_000.0 * self).round / 100_000.0) rescue self)
    return rv if [self].pack("f") == [rv].pack("f")
    self
  end
end

class Anim
  def initialize(path)
    @path = path
    @data = File.open(path, "rb").read
    @ofs = 0
  end

  def get(sz)
    raise "Format Error, trying to read past end of file" if @ofs+sz > @data.size
    rv = @data[@ofs, sz]
    @ofs += sz
    rv
  end

  def eof?
    @data.size == @ofs
  end

  def bytes_left
    @data.size - @ofs
  end

  def get_flt
    get(4).unpack("f")[0].pretty_single
  end

  def get_u4
    get(4).unpack("V")[0]
  end

  def get_i4
    get(4).unpack("i")[0]
  end

  def get_i2
    get(2).unpack("s")[0]
  end

  def get_u2
    get(2).unpack("v")[0]
  end

  def get_str
    get(get_u2)
  end

  # Does not deal with denormals, NaNs etc.
  def self.half_prec
    unless @half_prec
      @half_prec = {}
      (0..0xFFFF).each do |i|
        ip = [i].pack("v")
        sign     = ((i & 0x8000) == 1) ? -1.0 : 1.0
        if i & 0x7FFF == 0
          @half_prec[ip] = 0.0 * sign
        else
          exponent = 2.0 ** (((i >> 10) & 0x1F) - 15)
          mantissa = 1.0 + (i & 0x3FF) / 0x400.to_f
          @half_prec[ip] = sign * exponent * mantissa
        end
      end
    end
    @half_prec
  end

  def get_half
    Anim.half_prec[get(2)]
  end

  def get_fix2
    (get_i2/0x7FFF.to_f)
  end

  def parse
    result = []
    frames = get_u4
    result << frames
    result << get_u4 # model count ?
    result << get_flt
    result << [get_str, get_flt]
    # name and bone up the tree
    bones = get_u4
    result << bones.times.map{ [get_str, get_i4] }

    result << bones.times.map{ get_u4 } # bone numbers, 0...N
    result << bones.times.map{ get_u4 } # bone numbers, 0...N
    result << [get_i4, get_i4, get_i4]

    p bytes_left

    frames.times do
      frame = []
      bones.times do
        x,y,z,w = [get_fix2, get_fix2, get_fix2, get_fix2]
        norm = x**2 + y**2 + z**2 + w**2
        frame << [x,y,z,w]
      end
      result << frame
    end
    pp bytes_left
    result
  end
end


unless ARGV.size == 1
  STDERR.puts "#{$0} file.anim"
  exit 1
end

ase = Anim.new(ARGV[0])
pp ase.parse
