#!/usr/bin/env ruby

require "pathname"
require "pathname-glob"

Pathname("anim").glob("{etw,ntw}*.anim").each do |path|
  next if path.to_s.include?("testdata")
  rv = system "./unpack_anim_v1 #{path} >/dev/null"
  if rv
    puts "OK   #{path}"
  else
    puts "FAIL #{path}"
  end
end
