#!/usr/bin/env ruby

require_relative "anim"

class Anim < BaseAnim
  def parse
    header = [get_u4, get_flt, get_flt]
    raise unless header[0] == 1

    bone_count = get_u4
    bones = bone_count.times.map{ [get_str, get_i4] }
    frame_count = get_u4

    # binding.pry

    frames = frame_count.times.map{
      bone_count.times.map{
        14.times.map{get_fix2}
      }
    }

    extras =  get_u4.times.map{ get_u4.times.map{ get_str } }

    raise unless eof?

    {
      "header" => header,
      "bones" => bones,
      "frames" => frames,
      "extras" => extras,
    }
  end
end

unless ARGV.size == 1
  STDERR.puts "#{$0} file.anim"
  exit 1
end

ase = Anim.new(ARGV[0])
pp ase.parse
