#!/usr/bin/env ruby

require_relative "anim"

class Anim < BaseAnim
  def parse
    header = {"fps" => get_flt, "duration" => get_flt}

    bone_count = get_u4
    bones = bone_count.times.map{ [get_str, get_i4] }
    warn "Skeleton not -1" unless bones[0][1] == -1
    # Possible to have other unattached bones
    warn "Not valid bone attachments" unless bones[1..-1].map(&:last).grep_v(-1...bone_count).empty?

    frame_count = get_u4
    frames = frame_count.times.map{
      bone_count.times.map{
        [
          4.times.map{get_fix2},
          8.times.map{get_flt},
        ]
      }
    }

    extras =  get_u4.times.map{ get_u4.times.map{ get_str } }

    raise unless eof?

    {
      "header" => header,
      "bones" => bones,
      "frames" => frames,
      "extras" => extras,
    }
  end
end

unless ARGV.size == 1
  STDERR.puts "#{$0} file.anim"
  exit 1
end

ase = Anim.new(ARGV[0])
pp ase.parse
