#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class FactionReligion < EsfScript
  def run!(faction_to_change, religion)
    religion = "rel_#{religion}" unless religion =~ /\Arel_/
    update_faction(faction_to_change) do |faction|
      faction.xpath("s")[2].content = religion
      true
    end
  end
  
  def args
    %W[faction religion]
  end
end

FactionReligion.new
