#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class FactionCapital < EsfScript
  def run!(faction_to_change, new_capital_region)
    new_capital_id = region_name_to_id[new_capital_region]
    raise "Could not find region #{region_name}" unless new_capital_id
    update_faction(faction_to_change) do |faction|
      faction.xpath("i")[1].content = new_capital_id
      faction.xpath("i")[2].content = new_capital_id
      true
    end
  end
  
  def args
    %W[faction new_capital_region]
  end
end

FactionCapital.new
