#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class FactionReligion < EsfScript
  def run!(faction_to_change, religion)
    religion = "rel_#{religion}" unless religion =~ /\Arel_/
    update_faction(faction_to_change) do |faction|
      faction.xpath("s")[2].content = religion
      true
    end
  end
end

unless ARGV.size == 3
  STDERR.puts "Usage: #{$0} extracted_esf_directory faction religion"
  exit 1
end

xmldir = ARGV[0]
faction = ARGV[1]
religion = ARGV[2]

FactionReligion.new(xmldir).run!(faction, religion)
