#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class GiveTechnology < EsfScript
  def run!(faction_to_change, tech)
    update_factions_technologies(faction_to_change) do |techs|
      tech_node = techs.xpath("techs[@name='#{tech}']")
      raise "No such tech #{tech_node}" unless tech_node.size == 1
      tech_node[0]['unknown1'] = '0'
      # arbitrary value, doesn't seem to matter
      # real value is only available from db and varies from mod to mod
      tech_node[0]['research_points'] = '1000.0'
      true
    end
  end
end

unless ARGV.size == 3
  STDERR.puts "Usage: #{$0} extracted_esf_directory faction technology"
  exit 1
end

xmldir = ARGV[0]
faction = ARGV[1]
technology = ARGV[2]

GiveTechnology.new(xmldir).run!(faction, technology)
