#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class GiveAllTechnologies < EsfScript
  def run!(faction_to_change)
    update_factions_technologies(faction_to_change) do |techs|
      techs.xpath("techs").each do |tech_node|
        tech_node['status'] = '0'
        # arbitrary value, doesn't seem to matter
        # real value is only available from db and varies from mod to mod
        tech_node['research_points'] = '1000.0'
      end
      true
    end
  end
end

unless ARGV.size == 2
  STDERR.puts "Usage: #{$0} extracted_esf_directory faction"
  exit 1
end

xmldir = ARGV[0]
faction = ARGV[1]

GiveAllTechnologies.new(xmldir).run!(faction)
