#!/usr/bin/env ruby

require_relative "./esf_scripts"

class ListFactions < EsfScript
  def run!
    factions = []
    each_faction do |faction, faction_name|
      factions << faction_name
      false
    end
    puts factions.sort
  end
end

ListFactions.new
