#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class ListFactions < EsfScript
  def run!
    factions = []
    each_faction do |faction, faction_name|
      factions << faction_name
      false
    end
    puts factions.sort
  end
end

unless ARGV.size == 1
  STDERR.puts "Usage: #{$0} extracted_esf_directory"
  exit 1
end

xmldir = ARGV[0]

ListFactions.new(xmldir).run!
