#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class MakeFactionMajor < EsfScript
  def run!(faction_to_change)
    update_faction(faction_to_change) do |faction|
      faction.xpath("yes|no")[2].name = 'yes'
      true
    end
  end
  
  def args
    %W[faction]
  end
end

MakeFactionMajor.new
