#!/usr/bin/env ruby

require_relative "./esf_scripts"

class PathsUnExpand < EsfScript
  def run!
    update_each_file("pathfinding_areas*.xml") do |file|
      file.gsub(%r[</u4_ary>\s*<u4_ary>]m, "")
    end
  end
end

PathsUnExpand.new
