#!/usr/bin/env ruby

def parse_pgm(path_in)
  File.open(path_in, 'rb'){|fh_in|
    p5 = fh_in.readline
    sz = fh_in.readline
    l255 = fh_in.readline
    data_in = fh_in.read

    raise "Format error" unless p5 == "P5\n" and l255 == "255\n" and sz =~ /\A(\d+) (\d+)\n\z/
    xsz, ysz = $1.to_i, $2.to_i
    raise "Bad file size" unless data_in.size == xsz * ysz
    return [xsz, ysz, data_in]
  }
end

unless ARGV.size == 2
  STDERR.puts "Usage: #{$0} input.pgm output.pnm"
  exit 1
end

xsz, ysz, data = parse_pgm(ARGV[0])

data = data.unpack("C*")

File.open(ARGV[1], 'wb'){|fh|
  fh.print "P6\n#{xsz / 4} #{ysz}\n255\n"
  data_out = []
  until data.empty?
    data_out << data.shift
    data_out << data.shift
    data_out << data.shift
    a = data.shift
    raise "Alpha not 255" unless a == 255                    
  end
  fh.print data_out.pack("C*")                     
}
