#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class RemoveAllFortifications < EsfScript
  def run!
    update_each_xml("region/*.xml", "//rec[@type='BUILDING_MANAGER']") do |bm|
      is_present, building, = bm.xpath("*")
      next unless is_present.name == 'yes'
      next unless building.name == 'building'
      name = building['name']
      if ['settlement_fortifications', 'improved_settlement_fortifications'].include?(name)
        is_present.name = 'no'
        building.remove
        true
      else
        false
      end
    end
  end
end

unless ARGV.size == 1 and File.exist?(ARGV[0])
  STDERR.puts "Usage: #{$0} extracted_esf_directory"
  exit 1
end

xmldir = ARGV[0]

RemoveAllFortifications.new(xmldir).run!
