#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class RemoveResistanceToOccupation < EsfScript
  def run!
    update_each_xml("population/*.xml", "//rec[@type='POPULATION_CLASS']") do |pc|
      pc.xpath("i")[6].content = 0
      true
    end
  end
end

RemoveResistanceToOccupation.new
