#!/usr/bin/env ruby

require_relative "./esf_scripts"

class RemoveAllFortifications < EsfScript
  def run!
    update_each_xml("region*/*.xml", "//rec[@type='BUILDING_MANAGER']") do |bm|
      is_present, building, = bm.xpath("*")
      next unless is_present.name == 'yes'
      next unless building.name == 'building'
      name = building['name']
      if ['settlement_fortifications', 'improved_settlement_fortifications'].include?(name)
        is_present.name = 'no'
        building.remove
        true
      else
        false
      end
    end
  end
end

RemoveAllFortifications.new
