#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "esf_scripts"

class TurnsPerYear < EsfScript
  def run!(turns_per_year)
    update_each_xml("campaign_env/campaign_model*.xml", "//rec[@type='CAMPAIGN_CALENDAR']") do |calendar|
      calendar.xpath('*')[0].content = turns_per_year
      true
    end
  end
  
  def args
    %W[turns_per_year]
  end
  
  def check_args(turns_per_year)
    turns_per_year =~ /\A\d+\z/
  end
end

TurnsPerYear.new
