#!/usr/bin/env ruby

require "pp"

class CS2File
  attr_reader :data
  def initialize(stream)
    @data = ""
    @stream = stream
  end
  def ofs
    @data.size
  end
  
  def put_flt(v)
    @data << [v].pack("f")
  end
  def put_flts(vs)
    @data << vs.pack("f" * vs.size)
  end
  def put_u2(v)
    @data << [v].pack("v")
  end
  def put_u4(v)
    @data << [v].pack("V")
  end
  def put_str(s)
    s = s.unpack("U*").pack("v*")
    put_u2(s.size/2)
    @data << s
  end  
  def put_v3a(v3s)
    @data << [v3s.size].pack("V")
    v3s.each{|v3| put_flts(v3)}
  end
  def put_v2a(v2s)
    @data << [v2s.size].pack("V")
    v2s.each{|v2| put_flts(v2)}
  end
  def put_primary_data_array(pda)
    put_u4 pda.size
    pda.each_with_index{|row, i|
      put_u4 i
      if row[0] == true
        @data << "\x01"
      elsif row[0] == false
        @data << "\x00"
      else
        raise "Expected true or false, got: #{row[0]}"
      end
      @data << row[1..-1].pack("l*")
    }
  end
  def put_collision3d(tok)
    unless tok[0] =~ /\ACollision\((\d+)x\/(\d+)x\)\z/
      raise "Expected: Colission(Nx/Mx)"
    end
    d1sz, d2sz = $1.to_i, $2.to_i
    name = tok[1]
    v3a  = tok[2]
    pda  = tok[3]
    raise "Expected v3a size equal to #{d1sz}, got #{v3a.size}" unless d1sz == v3a.size
    raise "Expected primary data array size equal to #{d2sz}, got #{pda.size}" unless d2sz == pda.size

    put_str tok[1]
    put_v3a(v3a)
    put_primary_data_array(pda)
  end
  def put_array_of_collision3d(tok)
    put_u4 tok.size
    tok.each{|t|
      put_collision3d t
    }
  end
  def put_pipes(pipes)
    put_u4 pipes.size
    pipes.each{|s, v3a, u|
      put_str s
      put_v3a v3a
      put_u4 u
    }
  end
  def put_mystery2(ffua)
    put_u4 ffua.size
    ffua.each{|f1,f2,u|
      put_flt f1
      put_flt f2
      put_u4 u
    }
  end
  def put_mystery3(xx)
    # This is ugly pile of fail
    xx.map{|x|
      if x.is_a?(Float)
        put_flt x
      else
        put_u4 x
      end
    }
  end

  def shift_stream
    while true
      return nil if @stream.empty?
      tok = @stream.shift
      unless tok.is_a?(Array)
        raise "Expected correctly formatted token, got: #{tok.inspect}"
      end
      if tok[0] == :ofs
        assert_ofs!(tok[1])
      elsif tok[0] == :bytes_to_go
        warn "Expected 0 bytes to be left, got #{tok[1]} instead" unless tok[1] == 0
        assert_ofs!(tok[3])
      else
        return tok
      end
    end
  end

  def assert_ofs!(expected_ofs)
    warn "Expected offset: #{expected_ofs}, got instead: #{ofs}" unless ofs == expected_ofs
  end
  
  def assert_end_of_stream!
    tok = shift_stream
    raise "Tokens left after end of stream" unless tok.nil?
  end
  
  def shift_token(type)
    tok = shift_stream
    raise "Expected token #{type} got end of stream" unless tok
    raise "Expected token #{type} got #{tok[0]}" unless tok[0] == type
    tok[1..-1]
  end

  def repack!
    put_flts shift_token(:flt6)[0]
    put_str shift_token(:str)[0]
    put_flts shift_token(:flt8)[0]
    put_flts shift_token(:flt8)[0]

    u,s1,s2 = shift_token(:uss)
    put_u4 u
    put_str s1
    put_str s2
    put_flts shift_token(:flt8)[0]
    put_flts shift_token(:flt8)[0]
    
    cnt = shift_token(:cnt)[0]
    put_u4 cnt
    
    cnt.times{
      i = shift_token(:nth) # It doesn't actually do anything

      put_str shift_token(:str_a)[0]

      seq_num = shift_token(:seq_num)[0]
      put_u4 seq_num
      
      put_collision3d(shift_stream)
      put_array_of_collision3d(shift_stream)
      put_array_of_collision3d(shift_stream)
      put_array_of_collision3d(shift_stream)
      
      u, s = shift_token(:str_b)
      put_u4 u
      put_str s
      put_v3a shift_token(:v3a)[0]
      
      put_u4 shift_token(:mystery)[0]

      put_pipes shift_token(:pipes)[0]
      put_u4 shift_token(:mystery)[0]
      put_mystery2 shift_token(:mystery2)[0]
      put_mystery3 shift_token(:mystery3)
    }

    footer_size = shift_token(:footer_size)[0]
    footer1 = shift_token(:footer1)[0]
    footer2 = shift_token(:footer2)[0]
    raise "Footer1 size expected: #{footer_size}, got: #{footer1.size}" unless footer1.size == footer_size
    raise "Footer2 size expected: #{footer_size}, got: #{footer2.size}" unless footer2.size == footer_size

    put_u4 footer_size
    footer1.each{|v2a|
      put_v2a v2a
    }
    footer2.each{|v2a|
      put_v2a v2a
    }
    assert_end_of_stream!
  end
end

def cs2_pack(path_in, path_out)
  stream = eval(File.open(path_in, 'rb', &:read))
  cs2 = CS2File.new(stream)
  cs2.repack!
  File.open(path_out, 'wb'){|fh|
    fh.print cs2.data
  }
end

unless ARGV.size == 2
  STDERR.puts "Usage: #{$0} file.txt file.cs2.parsed"
  exit 1
end

path_in, path_out = *ARGV
cs2_pack(path_in, path_out)
