#!/usr/bin/env ruby

require "fileutils"

class FFTTTest
  attr_reader :fn
  def initialize(fn)
    @fn = fn
  end
  def out_dir
    "tmp/" + File.basename(fn).sub(/\.farm_fields_tile_texture\z/, "")
  end
  def remade_fn
    "tmp/recreated-" + File.basename(fn)
  end
  def run!
    FileUtils.rm_rf out_dir
    system "./fftt_unpack", fn, out_dir
    unless File.exist?(out_dir)
      puts "UNPACK FAILURE: #{fn}"
      return false
    end
    system "./fftt_pack", out_dir, remade_fn
    unless system 'diff', fn, remade_fn
      puts "DIFFER: #{fn}"
      return false
    else
      return true
    end
  end
end

samples = Dir["samples*/*.farm_fields_tile_texture"]

FileUtils.mkdir_p "tmp"

rv = Hash.new(0)
samples.each{|fn|
  res = FFTTTest.new(fn).run!
  rv[res] += 1
}
p rv
