#!/usr/bin/ruby

require "pp"

class FormatError < Exception
end

class Float
  def pretty_single
    rv = (((100_000.0 * self).round / 100_000.0) rescue self)
    return rv if [self].pack("f") == [rv].pack("f")
    self
  end
end

class VariantPartMeshUnpacker
  def initialize(file_name)
    @data = File.open(file_name, 'rb', &:read)
    @ofs  = 0
  end
  def size
    @data.size
  end
  def bytes_left
    @data.size - @ofs
  end

  # Basic data formats
  def get(size)
    raise FormatError.new("Not enough bytes: #{size} requested, only #{@data.size-@ofs} available") if size+@ofs > @data.size
    rv = @data[@ofs, size]
    @ofs += size
    rv
  end
  def get_u4
    get(4).unpack1("V")
  end
  def get_flt
    get(4).unpack1("f").pretty_single
  end
  def get_u2
    get(2).unpack1("v")
  end
  def get_byte
    get(1).unpack1("C")
  end
  # Size in UTF-16 characters, not bytes
  def get_str(size=nil)
    if size
      get(size*2).unpack("v*").pack("U*").sub(/\x00*\z/, "")
    else
      get(get_u2*2).unpack("v*").pack("U*")
    end
  end

  # Mid-level structures
  def get_4x4_matrix
    get(4*16).unpack("f*").map(&:pretty_single)
  end

  # Does not deal with denormals, NaNs etc.
  def self.half_prec
    unless @half_prec
      @half_prec = {}
      (0..0xFFFF).each do |i|
        ip = [i].pack("v")
        sign     = ((i & 0x8000) == 1) ? -1.0 : 1.0
        if i & 0x7FFF == 0
          @half_prec[ip] = 0.0 * sign
        else
          exponent = 2.0 ** (((i >> 10) & 0x1F) - 15)
          mantissa = 1.0 + (i & 0x3FF) / 0x400.to_f
          @half_prec[ip] = sign * exponent * mantissa
        end
      end
    end
    @half_prec
  end

  def get_half
    VariantPartMeshUnpacker.half_prec[get(2)]
  end

  def get_pbvec
    #  -1.0 to +1.0
    get(3).unpack("C*").map{|x|
      (x / 255.0) * 2.0 - 1.0
    }
  end

  # High level structures
  def get_lod_vertex
    {
      :position0   => [get_half, get_half, get_half],
      :u           => get_half,
      :position1   => [get_half, get_half, get_half],
      :v           => get_half,
      :flags       => [get_half, get_half, get_half, get_half],
      :normal0     => get_pbvec,
      :bone0_index => get_byte,
      :normal1     => get_pbvec,
      :bone1_index => get_byte,
      :tangent     => get_pbvec,
      :bone0_weight=> get_byte,
      :binormal    => get_pbvec,
      :instance    => get_byte,
    }
  end
  def get_lod
    vertices_count = get_u4
    vertex_indices_count = get_u4
    raise FormatError.new("Number of triangle indices should be divisible by 3") if vertex_indices_count % 3 != 0

    vertices = (0...vertices_count).map{ get_lod_vertex }
    vertex_indices = (0...vertex_indices_count/3).map{ get(6).unpack("vvv")}

    [vertices, vertex_indices]
  end
  def get_attachment
    {
      :name => get_str(16),
      :matrix => get_4x4_matrix,
      :bone_index => get_u4,
   }
  end
  def get_shader_setting_basic
    {
      :name  => get_str(32),
      :value => get_flt,
    }
  end
  def get_shader_setting_advanced
    {:name => get_str(32), :full_name => get_str, :data => get(16).unpack("f*").map(&:pretty_single)}
  end
  def parse_type_1
    attachments_count              = get_u4
    lod_levels                     = get_u4
    vertices_count                 = get_u4
    vertex_indices_count           = get_u4
    shader_settings_basic_count    = get_u4
    shader_settings_advanced_count = get_u4

    lods = (0...lod_levels).map{ get_lod }
    attachments = (0...attachments_count).map{ get_attachment }
    shader_settings_basic = (0...shader_settings_basic_count).map{ get_shader_setting_basic }
    shader_settings_advanced = (0...shader_settings_advanced_count).map{ get_shader_setting_advanced }

    raise FormatError.new("Vertex count incorrect") unless vertices_count == lods.map{|x,y| x.size}.inject(&:+)
    raise FormatError.new("Vertex indices count incorrect") unless vertex_indices_count == 3*lods.map{|x,y| y.size}.inject(&:+)
    raise FormatError.new("Bytes left: #{bytes_left}") if bytes_left > 0

    {
      :type => 1,
      :lods => lods,
      :attachments => attachments,
      :shader_settings_basic => shader_settings_basic,
      :shader_settings_advanced => shader_settings_advanced,
    }
  end
  def parse
    raise FormatError.new unless get(4) == "VMPF"
    raise FormatError.new unless get_u4 == 0
    format_type = get_u4
    case format_type
    when 0
      warn "Format 0 not yet supported"
      nil
    when 1
      parse_type_1
    when 2
      warn "Format 2 not yet supported"
      nil
    else
      raise FormatError.new "Only known types are 0, 1, and 2, not #{format_type}"
    end
  end
end

if ARGV.size > 0
  samples = ARGV
else
  samples = Dir["samples/*"].sort_by{|fn| File.size(fn) }[0, 40]
end

samples.each do |file_name|
  vpm = VariantPartMeshUnpacker.new(file_name)
  puts "Converting #{file_name}:"
  data = vpm.parse
  out = ""
  PP.pp(data, out, 150)
  puts out
  puts ""
end
