#!/usr/bin/env ruby

class File
  def self.write(file_name, data)
    File.open(file_name, 'wb'){|fh|
      fh.write data
    }
  end
end

def load_txt(file_name)
  eval(File.open(file_name, 'rb', &:read))
end

def save_ase(data, file_name)
  bindata = ""
  version = data[0]
  bindata << [version].pack("V")

  if version == 2
    samples = data[1..-1]
  else
    bindata << [data[1]].pack("V")
    samples = data[2..-1]
  end

  bindata << [samples.size].pack("V")
  samples.each do |sample|
    bindata << sample.pack("fVV")
  end
  File.write(file_name, bindata)
end

unless ARGV.size == 2
  STDERR.puts "#{$0} file.txt file.anim_sound_event"
  exit 1
end

save_ase(load_txt(ARGV[0]), ARGV[1])
