#!/usr/bin/env ruby

require_relative "../esf_script"

class FactionCapital < EsfScript
  def call(faction_to_change, new_capital_region)
    new_capital_id = region_name_to_id[new_capital_region]
    raise "Could not find region #{new_capital_region}" unless new_capital_id
    update_faction(faction_to_change) do |faction|
      faction.xpath("i")[1].content = new_capital_id
      faction.xpath("i")[2].content = new_capital_id
      true
    end
  end

  def args
    %W[faction new_capital_region]
  end
end

FactionCapital.new
