#!/usr/bin/env ruby

require_relative "../esf_script"

class GiveAllTechnologies < EsfScript
  def call(faction_to_change)
    update_factions_technologies(faction_to_change) do |techs|
      techs.xpath("techs").each do |tech_node|
        tech_node['status'] = '0'
        # arbitrary value, doesn't seem to matter
        # real value is only available from db and varies from mod to mod
        tech_node['research_points'] = '1000.0'
      end
      true
    end
  end

  def args
    %W[faction]
  end
end

GiveAllTechnologies.new
