#!/usr/bin/env ruby

require_relative "../esf_script"

class MakeAllFactionsMajor < EsfScript
  def call
    update_each_faction do |faction, faction_name|
      faction.xpath("yes|no")[2].name = 'yes'
      true
    end
  end
end

MakeAllFactionsMajor.new
