#!/usr/bin/env ruby

require_relative "../esf_script"

class MakeMoreVanillaFactionsPlayable < EsfScript
  def call
    # Make default vanilla states playable *including* protectorates
    # Not every one of them has sensible gameplay options
    # If you want to play protectorates you'll need to fix diplomacy options
    # reset_diplomacy script will work here

    factions = %W[
      bavaria
      chechenya_dagestan
      cherokee
      denmark
      genoa
      georgia
      hannover
      huron
      inuit
      iroquoi
      knights_stjohn
      morocco
      mughal
      mysore
      papal_states
      piedmont_savoy
      plains
      portugal
      pueblo
      safavids
      venice
      westphalia
      wurttemberg

      barbary_states
      courland
      crimean_khanate
      louisiana
      new_spain
      saxony
      thirteen_colonies
    ]

    factions.each do |faction_to_change|
      make_faction_playable(faction_to_change)
    end
  end
end

MakeMoreVanillaFactionsPlayable.new
