#!/usr/bin/env ruby

require_relative "../esf_script"

class MakeFactionMinor < EsfScript
  def call(faction_to_change)
    update_faction(faction_to_change) do |faction|
      faction.xpath("yes|no")[2].name = 'no'
      true
    end
  end

  def args
    %W[faction]
  end
end

MakeFactionMinor.new
