#!/usr/bin/env ruby

require_relative "../esf_script"

class MakeFactionPlayable < EsfScript
  def call(faction_to_change)
    make_faction_playable(faction_to_change)
  end

  def args
    %W[faction]
  end
end

MakeFactionPlayable.new
