#!/usr/bin/env ruby

unless ARGV.size == 1
  STDERR.puts "Usage: #{$0} target"
  exit 1
end

orig = 'output/dmuc_cstartpos_orig'
target = ARGV[0]

if File.exist?(target)
  STDERR.puts "#{target} already exists"
  exit 1
end

system *%W[cp -a #{orig} #{target}]
system *%W[./scripts/make_more_vanilla_factions_playable #{target}]
system *%W[./scripts/remove_all_fortifications #{target}]
system *%W[./scripts/remove_resistance_to_occupation #{target}]
system *%W[./scripts/reset_diplomacy #{target}]
system *%W[./scripts/make_faction_major #{target} portugal]
system *%W[./scripts/make_faction_major #{target} venice]
system *%W[./scripts/make_faction_major #{target} denmark]
# system *%W[./scripts/give_all_techs #{target} *]
system *%W[./scripts/rescale_populations #{target} 2500 250000]
system *%W[./xml2esf #{target} #{target}.esf]
