#!/usr/bin/env ruby

require_relative "../esf_script"

class RemoveResistanceToOccupation < EsfScript
  def call
    update_each_xml("population/*.xml", "//population_class") do |pc|
      # Do not remove positive resistance (against raids by enemy armies)
      pc['resistance'] = '0' if pc['resistance'].to_i < 0
      pc['foreign'] = '0' if pc['foreign'].to_i < 0
      true
    end
  end
end

RemoveResistanceToOccupation.new
