#!/usr/bin/env ruby

require "fileutils"

class TileListTest
  attr_reader :fn
  def initialize(fn)
    @fn = fn
  end
  def out_path
    "tmp/" + File.basename(fn).sub(/\.tile_list\z/, "") + ".txt"
  end
  def remade_fn
    "tmp/recreated-" + File.basename(fn)
  end
  def run!
    system "./tile_list_unpack", fn, out_path
    unless File.exist?(out_path)
      puts "UNPACK FAILURE: #{fn}"
      return false
    end
    system "./tile_list_pack", out_path, remade_fn
    unless system 'diff', fn, remade_fn
      puts "DIFFER: #{fn}"
      return false
    else
      return true
    end
  end
end

if ARGV.empty?
  samples = Dir["samples_8/*.tile_list"]
else
  samples = ARGV
end

FileUtils.rm_rf "tmp"
FileUtils.mkdir_p "tmp"

rv = Hash.new(0)
samples.each do |fn|
  res = TileListTest.new(fn).run!
  rv[res] += 1
end
p rv
