-- Add this to OnWorldCreated in scripting.lua
-- If you play some mod which changes list of factions, adjust factionsList table

-- list of all factions in the game
factionsList = {"afghanistan",
                "american_rebels",
                "amerind_rebels",
                "austria",
                "austrian_rebels",
                "barbary_rebels",
                "barbary_states",
                "bavaria",
                "britain",
                "british_rebels",
                "british_settler_rebels",
                "chechenya_dagestan",
                "cherokee",
                "colombia",
                "cossack_rebels",
                "courland",
                "crimean_khanate",
                "denmark",
                "dutch_rebels",
                "european_settler_rebels",
                "france",
                "french_rebels",
                "french_settler_rebels",
                "genoa",
                "georgia",
                "greece",
                "greek_rebels",
                "hannover",
                "hessen",
                "holstein_gottorp",
                "hungary",
                "huron",
                "india_settler_rebels",
                "inuit",
                "ireland",
                "iroquoi",
                "italian_rebels",
                "khanate_khiva",
                "knights_stjohn",
                "louisiana",
                "mamelukes",
                "maratha",
                "maratha_rebels",
                "mecklenburg",
                "mexico",
                "middle_east_settler_rebels",
                "morocco",
                "mughal",
                "mughal_rebels",
                "mysore",
                "naples_sicily",
                "netherlands",
                "new_spain",
                "norway",
                "ottoman_rebels",
                "ottomans",
                "papal_states",
                "persian_rebels",
                "piedmont_savoy",
                "pirates",
                "plains",
                "poland_lithuania",
                "portugal",
                "portugese_rebels",
                "powhatan",
                "prussia",
                "prussian_rebels",
                "pueblo",
                "punjab",
                "quebec",
                "russia",
                "safavids",
                "saxony",
                "scandinavian_rebels",
                "scotland",
                "sikh_rebels",
                "slavic_rebels",
                "spain",
                "spanish_rebels",
                "spanish_settler_rebels",
                "sweden",
                "swiss_confederation",
                "thirteen_colonies",
                "tuscany",
                "united_states",
                "venice",
                "virginia",
                "virginia_colonists",
                "westphalia",
                "wurttemberg"}

local function OnWorldCreated()
  for k1,v1 in ipairs(factionsList) do
    for k2,v2 in ipairs(factionsList) do
      scripting.game_interface:force_diplomacy(v1,v2, "technology", false, false)
    end
  end
end
