#!/usr/bin/env ruby

class Markers
  def initialize(path)
    @data = File.open(path, 'rb').read
    @ofs = 0
  end

  def get(sz)
    raise "Requested reading past end of file (#{@path}:#{@ofs}) - #{sz}" if @ofs + sz > @data.size
    rv = @data[@ofs, sz]
    @ofs += sz
    rv
  end
  
  def get_u2
    get(2).unpack("v")[0]
  end
  
  def get_str
    get(get_u2*2).unpack("v*").pack("U*")
  end
  
  def parse
    parsed = []
    while @ofs < @data.size
      str    = get_str
      flts   = get(16*4).unpack("f*")
      parsed << [str, *flts]
    end
    parsed
  end
end

unless ARGV.size == 2
  STDERR.puts "Usage: #{$0} input.markers output.txt"
  exit 1
end

data = Markers.new(ARGV[0]).parse

File.open(ARGV[1], 'wb') do |fh|
  fh.puts data.map(&:inspect)
end
