#!/usr/bin/env ruby

require "pp"

class Float
  def pretty_single
    return self if nan?
    begin
      rv = (100_000.0 * self).round / 100_000.0
      return rv if self != rv and [self].pack("f") == [rv].pack("f")
      self
    rescue
      self
    end
  end
end

class Markers
  def initialize(path)
    @path = path
    @data = File.open(path, 'rb', &:read)
    @ofs = 0
  end

  def bytes_left
    @data.size - @ofs
  end

  def eof?
    @data.size == @ofs
  end

  def get(sz)
    raise "Requested reading past end of file (#{@path}:#{@ofs}) - #{sz}" if @ofs + sz > @data.size
    rv = @data[@ofs, sz]
    @ofs += sz
    rv
  end
  
  def get_u1
    get(1).unpack("C")[0]
  end
  
  def get_u2
    get(2).unpack("v")[0]
  end
  
  def get_u4
    get(4).unpack("V")[0]
  end
  
  def get_str
    get(get_u2*2).unpack("v*").pack("U*")
  end
  
  def get_flt
    get(4).unpack("f")[0].pretty_single
  end
  
  def get_ary(&blk)
    (0...get_u4).map(&blk)
  end

  def get_ary2(&blk)
    (0...get_u2).map(&blk)
  end
  
  def get_u4_or_flt
    v = get(4)
    vi = v.unpack("V")[0]
    vf = v.unpack("f")[0]
    if vi >= 0 and vi <= 255
      vi
    else
      vf
    end
  end
  
  def parse1
    p get_str
    p [get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u2]
    p [get_u4, get_str]
    p get(20).unpack("V*")
    PP.pp get_ary{ [get_flt, get_flt, get_flt, get_flt, get_flt, get_flt, get_flt, get_u1, get_str]}, $>, 150
    pp get_ary2{ [get_u2, get_str, get_ary{ get_u4 }] }
    warn "Still #{bytes_left} bytes to go at #{@path}:#{@ofs}" unless eof?
  end
  
  def parse2
    p get_str
    p [get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u2]
    p [get_u4, get_str]
    p get(20).unpack("V*")
    PP.pp get_ary{ [get_flt, get_flt, get_flt, get_flt, get_flt, get_flt, get_flt, get_u1, get_str]}, $>, 150
    warn "Still #{bytes_left} bytes to go at #{@path}:#{@ofs}" unless eof?
  end
  
  def parse3
    p get_str
    p [get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u4, get_u2]
    p [get_u4, get_str]
    p get(20).unpack("V*")
    PP.pp get_ary{
      [get_u4, get_flt, get_flt, get_flt, get_u4_or_flt]
    }, $>, 150
    pp get_ary2{ [get_u2, get_str, get_ary{ get_u4 }] }
    warn "Still #{bytes_left} bytes to go at #{@path}:#{@ofs}" unless eof?
  end
end

Markers.new("samples/shogun2/campaign_prop_marker.markers").parse1

puts "----"

Markers.new("samples/shogun2/campaign_display_model_marker.markers").parse2

puts "----"

Markers.new("samples/shogun2/campaign_display_overlay_marker.markers").parse2

puts "----"

Markers.new("samples/shogun2/campaign_display_emitter_marker.markers").parse3



# unless ARGV.size == 2
#   STDERR.puts "Usage: #{$0} input.markers output.txt"
#   exit 1
# end

# data = Markers.new(ARGV[0]).parse2
# 
# File.open(ARGV[1], 'wb') do |fh|
#   fh.puts data.map(&:inspect)
# end
