#!/usr/bin/env ruby

require "pp"

Dir["samples/*"].each do |sample|
  tsv = "tmp/" + File.basename(sample, ".atlas") + ".tsv"
  out = "tmp/" + File.basename(sample, ".atlas") + ".atlas"
  
  system "./atlas_unpack", sample, tsv
  system "./atlas_pack", tsv, out
  system "diff", sample, out
end
