#!/usr/bin/env ruby

require "fileutils"
require_relative "./lib/esf_converter"

class String
  def unpack1(*args)
    unpack(*args).first
  end unless method_defined? :unpack1
end

verbose = false
semantic = false
while ARGV[0] == "--verbose" or ARGV[0] == "--quiet" or ARGV[0] == "--semantic"
  case ARGV.shift
  when "--verbose"
    verbose = true
  when "--quiet"
    verbose = true
  when "--semantic"
    semantic = true
  end
end

unless ARGV.size == 2
  STDERR.puts <<EOF
Usage:
  #{$0} input.esf output_dir
For progress bar:
  #{$0} --verbose input.esf output_dir
EOF
  exit 1
end

in_file = File.open(ARGV[0], 'rb')
out_dir = ARGV[1]
if File.exist?(out_dir)
  STDERR.puts "#{out_dir} already exists"
  exit 1
end

esf_converter = EsfConverter.new(in_file, out_dir)
thr = esf_converter.progressbar_thread if verbose
esf_converter.convert!
esf_converter.report_semantic_failures! if semantic
