RecordTypes = {
    :"CAI_MILITARY_STRENGTH_FOR_FACTION"              => [["u4","i4","i4","i4"], [:a,:b,:c,:d]],
    :"CAI_TAS_ANALYSIS_THREAT"                        => [["i4"], [:value]],
    :"CAI_TAS_ANALYSIS_SUPPORT"                       => [["i4"], [:value]],
    :"CAI_RELATIVE_ABSOLUTE_STRENGTH_ANALYSIS_BASE"   => [["i4"], [:value]],
    :"CAI_COMPOSITE_VALUE_ANALYSIS"                   => [["i4"], [:value]],
    :"CAI_RELATIVE_ABSOLUTE_STRENGTH_ANALYSIS_MOBILE" => [["u4"], [:value]],
    :"CAI_AREA_OF_INTEREST_ANALYSIS_RESOURCE_MOBILE"  => [["u4"], [:value]],
    :"CAI_NAVY_STRENGTH_THEATRE_ANALYSIS"             => [["u4"], [:value]],
    :"CAI_CONSTRUCTION_BALANCE_ANALYSIS_REGION"       => [["u4"], [:value]],
    :"CAI_RELATIVE_ABSOLUTE_STRENGTH_ANALYSIS_UNIT"   => [["u4"], [:value]],
    :"CAI_COMPOSITE_REGION_ANALYSIS"                  => [["u4"], [:value]],
    :"GARRISON_RESIDENCE"                             => [["u4"], [:value]],
    :"CAI_TAS_ANALYSIS_THREAT_AND_SUPPORT"            => [["u4","flt","flt"], [:a, :b, :c]],
    :"CAI_ARMED_CITIZENRY_ANALYSIS"                   => [["u4","i4"], [:a, :b]],
    :"CAI_PORT_ANALYSIS"                              => [["u4","i4"], [:a, :b]],
    :"CAI_FACTION_RELATION_ENTRY"                     => [
                                                           ["u4", "u4", "u4", "bool", "bool", "bool", "flt", "flt", "u4"],
                                                           [:a, :b, :c, :d, :e, :f, :g, :h, :i],
                                                         ],
    :"BUILDING"                                       => [["u4", "str", "str", "str"], [:percent, :building, :faction, :government]],
    :"DATE" => [["u4", "ascii"], [:year, :season]],
    :UNIT_RECORD_KEY => [["str"], [:key]],
    :LAND_RECORD_KEY => [["str"], [:key]],
    :NAVAL_RECORD_KEY => [["str"], [:key]],
    :PORTRAIT_DETAILS => [["str", "str", "str", "i4"], [:a, :b, :c, :d]],
    :GOVERNORSHIP_TAXES => [["u4", "u4", "byte", "byte"], [:a, :b, :c, :d]],
    :CAMPAIGN_PLAYER_SETUP_INGAME_MODIFIABLES => [["i4", "i4", "i4", "bool"], [:a, :b, :c, :d]],

    # :CAMPAIGN_BONUS_VALUE => [["u4", "i4", "flt", "str"], [:a, :b, :c, :d]],
}

ElementTypes = {
    :groundtype_index   => [["str"], [:group_type]],
    :"connectivity"     => [["u4", "u4", "u4"],  [:a, :b, :c]],
    :"REGION_KEYS"      => [["str"],  [:region]],
    :"REGION_OWNERSHIPS"=> [["str", "str"],  [:region, :faction]],
    :"FACTION_INFOS"    => [["str", "str", "bool", "bool", "i4", "str", "str", "i4"],  [:faction, :portrait, :a, :b, :c, :description_id, :flag_path, :d]],
    :"DIPLOMACY_RELATIONSHIP_ATTITUDES_ARRAY" => [["i4", "i4", "i4", "bool", "i4", "bool"],  [:a, :b, :c, :d, :e, :f]],
    :"AgentAttributes"  => [["str", "i4"], [:attribute, :level]],
    :"TRAIT"            => [["str", "i4"], [:trait, :level]],
    :"AgentAbilities"   => [["str", "i4", "str"], [:ability, :level, :extra]],
    :"CAI_BDI_COMPONENT_BLOCK_OWNS" => [["u4", "u4", "flt", "flt", "u4"], [:a, :b, :c, :d, :e]],
    :"RELIGION_BREAKDOWN" => [["str", "flt"], [:religion, :percent]],
    :PORT_INDICES        => [["str", "u4"], [:slot, :index]],
    :SETTLEMENT_INDICES  => [["str", "u4"], [:region, :index]],
    :CAI_HISTORY_EVENT_HTML_CLASSES => [["ascii"], [:class]],
    :AgentAttributeBonuses => [["str", "u4"], [:attribute, :bonus]],
}
