#!/usr/bin/env ruby

require "fileutils"

class SampleTest
  def initialize(filename)
    @filename = filename
  end
  def source
    "samples/#{@filename}"
  end
  def xmldir
    "tmp/" + @filename.gsub(".", "_") + "_dir"
  end
  def recreated
    "tmp/recreated_#{@filename}"
  end
  def size
    File.size(source)
  end
  def ruby
    # %W[time jruby --server -J-Xmx2048m]
    %W[ruby]
  end
  def run!
    puts "Converting #{@filename}"
    FileUtils.rm_rf xmldir
    system *(ruby + ["./esf2xml", source, xmldir])

    puts "Recreating #{@filename}"
    FileUtils.rm_rf recreated
    system *(ruby + ["./xml2esf", xmldir, recreated])
    
    system "diff", source, recreated
  end
end

sample_tests = [
  "trade_routes.esf",
  "sea_grids.esf",
  "poi.esf",
  "pathfinding.esf",
  "regions.esf",
  "bmd.dat",
  "startpos.esf",
].map{|filename| SampleTest.new(filename)}.sort_by(&:size)

FileUtils.mkdir_p "tmp"
sample_tests.each do |test|
  test.run!
end
