#!/usr/bin/env ruby

ruby = RUBY_PLATFORM == 'java' ? "jruby" : "ruby"

def windows?
  if RUBY_PLATFORM == 'java'
    require "java"
    java.lang.System.getProperty("os.name") =~ /\bwin/i
  else # not /darwin/
    RUBY_PLATFORM =~ /\bwin/i
  end
end

quiet = nil
if ARGV[0] == "--quiet" or ARGV[0] == "--verbose"
  quiet = ARGV.shift
end

unless ARGV.size == 2
  STDERR.puts <<EOF
Usage:
  #{$0} input.esf output_dir
To hide progress bar:
  #{$0} --quiet input.esf output_dir
EOF
  exit 1
end

in_file = ARGV[0]
out_dir = ARGV[1]
if File.exist?(out_dir)
  STDERR.puts "#{out_dir} already exists"
  exit 1
end

system *[ruby, "esf2xml", quiet, in_file, out_dir].compact
if File.exist?("#{out_dir}/compressed_data.esf.xz")
  if windows?
    system "./lzma", "d", "#{out_dir}/compressed_data.esf.xz", "#{out_dir}/compressed_data.esf"
  else
    system "lzma", "-dk", "#{out_dir}/compressed_data.esf.xz"
  end
end
if File.exist?("#{out_dir}/compressed_data.esf")
  system *[ruby, "./esf2xml", quiet, "#{out_dir}/compressed_data.esf", "#{out_dir}/compressed_data"].compact
end
