#!/usr/bin/env ruby

require "pathname"

class CreateLedger
  def initialize(save_path)
    @save_path = Pathname(save_path)
  end

  def unpacked_path
    @unpacked_path ||= Pathname(@save_path.to_s.sub(/\.(empire_save|esf)\z/, ""))
  end

  def ledger_root
    @unpacked_path + "ledger"
  end
  
  def ledger_scripts
    {
      alliance_clusters: "list_alliance_clusters",
      buildings: "list_buildings",
      diplomacy: "list_diplomacy",
      faction_ids: "list_faction_ids",
      factions: "list_factions",
      government: "analyze_government",
      military: "list_military",
      navy: "list_navy",
      region_ids: "list_region_ids",
      region_ownership: "list_region_ownership",
      research: "list_research",
      resistance: "list_resistance",
      treasury: "list_treasury",
    }
  end

  def unpack_save!
    return if unpacked_path.exist?
    raise unless @save_path.extname == ".empire_save"
    system "#{__dir__}/../../esf2xml", @save_path.to_s, unpacked_path.to_s
  end

  def call_script!(page, script)
    output_path = ledger_root + "#{page}.txt"
    return if output_path.exist?
    system "#{__dir__}/#{script} '#{unpacked_path.to_s}' >'#{output_path.to_s}'"
  end

  def call
    unpack_save!
    ledger_root.mkpath
    ledger_scripts.each do |page, script|
      call_script! page, script
    end
  end
end

# This accidentally works both ways
unless ARGV.size == 1
  STDERR.puts "Usage: #{$0} file.empire_save"
  STDERR.puts "   or: #{$0} unpacked_esf_dir"
  exit 1
end

CreateLedger.new(ARGV[0]).call
