#!/usr/bin/env ruby

require_relative "../esf_script"

class ListTreasuryByFaction < EsfScript
  def call
    factions = []
    each_faction do |faction, faction_name|
      starting_treasury = faction.xpath("rec[@type='FACTION_ECONOMICS']/i")[0].content.to_i
      factions << [faction_name, starting_treasury]
    end
    puts factions.sort.map{|faction, treasury| "#{faction}: #{treasury}"}
  end
end

ListTreasuryByFaction.new
