#!/usr/bin/env ruby

require_relative "../esf_script"

class ListFactionIds < EsfScript
  def call
    factions = []
    each_faction do |faction, faction_name|
      id = faction.xpath("i")[0].content
      factions << [faction_name, id]
    end
    puts factions.sort.map{|faction_name, id| "#{faction_name}: #{id}"}
  end
end

ListFactionIds.new
