#!/usr/bin/env ruby

require_relative "../esf_script"

class ListRegionOwnership < EsfScript
  def call
    regions_by_faction.sort_by{|k,v| [-v.size, k]}.each do |faction_name, regions|
      puts "#{faction_name} (#{regions.size}):"
      puts regions.map{|r| "* #{r}"}
    end
  end
end

ListRegionOwnership.new
