#!/usr/bin/env ruby

require_relative "../esf_script"

class ListFactions < EsfScript
  def call
    factions = []
    each_faction do |faction, faction_name|
      factions << faction_name
    end
    puts factions.sort
  end
end

ListFactions.new
