#!/usr/bin/env ruby

require_relative "../esf_script"
require "json"

class ListBuildings < EsfScript
  def call
    output = []
    each_building_slot do |data|
      output << data
    end
    output.sort_by!{|x| x[:id].sub(/.*?:/, "")}
    puts output.map(&:to_json)
  end
end

ListBuildings.new
