#!/usr/bin/env ruby

require_relative "../esf_script"

class ListDiplomacy < EsfScript
  def call
    each_faction_diplomatic_relation do |faction1, faction2, rel|
      puts [faction1, faction2, rel].join("\t")
    end
  end
end

ListDiplomacy.new
